llist.c: llist.h
	tcc -c llist.c

llist.obj: llist.c

tests.c:
	tcc -c tests.c

tests.obj: llist.obj tests.c

compile: tests.obj
	tcc -c -I..\ ..\base.c
	tcc tests.obj llist.obj base.obj

run: compile
	tests.exe

clean:
	rescan
	del *.obj
	del *.exe
	del *.log
