OBJECTS = list.obj tester.obj cli.obj
CC = tcc
FLAGS = -c -I..\include

default: clean all

list.obj: list.c list.h
	$(CC) $(FLAGS) list.c

tests.obj: tests.c
	$(CC) $(FLAGS) tests.c

contacts.obj: contacts.c
	$(CC) $(FLAGS) -c contacts.c

cli.obj: ..\include\cli.c
	$(CC) $(FLAGS) ..\include\cli.c

tester.obj: ..\include\tester.c
	$(CC) $(FLAGS) ..\include\tester.c

tests.exe: tests.obj $(OBJECTS)
	$(CC) tests.obj $(OBJECTS)

contacts.exe: contacts.obj $(OBJECTS)
	$(CC) contacts.obj $(OBJECTS)

all: tests.exe contacts.exe

run-contacts: CONTACTS.EXE
	CONTACTS.EXE

clean:
	rescan
	del *.obj
	del *.exe
	del *.log
	del *.dat
