list.c: list.h
	tcc -c list.c

list.obj: list.c

tests.c:
	tcc -c tests.c

tests.obj: list.obj tests.c

compile: tests.obj
	tcc -c -I..\ ..\base.c
	tcc tests.obj list.obj base.obj

run: compile
	tests.exe

clean:
	rescan
	del *.obj
	del *.exe
	del *.log
