OBJECTS = list.obj base.obj
CC = tcc

default: clean all

list.obj: list.c list.h
	$(CC) -c list.c

tests.obj: tests.c
	$(CC) -c tests.c

contacts.obj: contacts.c
	$(CC) -c contacts.c

base.obj: ..\base.c
	$(CC) -c -I..\ ..\base.c

tests.exe: tests.obj $(OBJECTS)
	$(CC) tests.obj $(OBJECTS)

contacts.exe: contacts.obj $(OBJECTS)
	$(CC) contacts.obj $(OBJECTS)

all: tests.exe contacts.exe

run-contacts: CONTACTS.EXE
	CONTACTS.EXE

clean:
	rescan
	del *.obj
	del *.exe
	del *.log
	del *.dat
